const JSON = [
  {
    id: 1,
    nome: "Perfume Masc. Esp.",
    descricao: "descritivo",
    tipo: {
      id: 2,
      tipo: "Floral",
    },
    marca: {
      id: 2,
      nome: "Dolce & Gabanna",
    },
    genero: "M",
    especial: true,
    estoque: 10000,
    precoNormal: 10.04,
    oferta: false,
    precoOferta: 9.99,
    precoVenda: 10.04,
    mediaAvaliacao: 2,
  },
  {
    id: 2,
    nome: "Perfume Masc. Ofe.",
    descricao: "descritivo",
    tipo: {
      id: 1,
      tipo: "Cítrico",
    },
    marca: {
      id: 5,
      nome: "Channel",
    },
    genero: "M",
    especial: false,
    estoque: 10000,
    precoNormal: 120.04,
    oferta: true,
    precoOferta: 119.99,
    precoVenda: 119.99,
    mediaAvaliacao: 3,
  },
  {
    id: 3,
    nome: "Perfume Fem. Esp.",
    descricao: "descritivo",
    tipo: {
      id: 5,
      tipo: "Aromático",
    },
    marca: {
      id: 1,
      nome: "Dior",
    },
    genero: "F",
    especial: true,
    estoque: 10000,
    precoNormal: 30.04,
    oferta: false,
    precoOferta: 29.99,
    precoVenda: 30.04,
    mediaAvaliacao: 3,
  },
  {
    id: 4,
    nome: "Perfume Uni. Ofe.",
    descricao: "descritivo",
    tipo: {
      id: 2,
      tipo: "Floral",
    },
    marca: {
      id: 1,
      nome: "Dior",
    },
    genero: "U",
    especial: false,
    estoque: 10000,
    precoNormal: 140.04,
    oferta: true,
    precoOferta: 139.99,
    precoVenda: 139.99,
    mediaAvaliacao: 5,
  },
  {
    id: 5,
    nome: "Perfume Uni. Esp.",
    descricao: "descritivo",
    tipo: {
      id: 2,
      tipo: "Floral",
    },
    marca: {
      id: 1,
      nome: "Dior",
    },
    genero: "U",
    especial: true,
    estoque: 0,
    precoNormal: 150.04,
    oferta: false,
    precoOferta: 149.99,
    precoVenda: 150.04,
    mediaAvaliacao: 4,
  },
];

export default JSON;
